db:
  image: mysql
  volumes:
    - ~/alura/blog-alura/database/:/var/lib/mysql/
  environment:
    - MYSQL_ROOT_PASSWORD=test123

blog:
  image: wordpress
  environment:
    - WORDPRESS_DB_PASSWORD=test123
  links:
    - db:mysql
  ports:
    - 8888:80
